### ISSUE TITLE
ServiceFactory fails for methods that return void

### ISSUE THREAD

**Issue by pvangool** [dnault/therapi-json-rpc#2]
David,

The client service factory is working great. But I ran into 1 issue.

I have a service like:

```
@Remotable("prefs")
public interface PrefsService {

   void set(Map<String, String> map);

   Map<String, String> get();

   void delete(Set<String> keys);

}
```

When I call ‘delete’ our JSON-RPC2 server returns:

{"result":{},"id":1234,"jsonrpc":"2.0","procTime":61}

The therapi client is not able to handle that ‘void’ response. I get the following Jackson exception:

Exception in thread "main" java.lang.IllegalArgumentException: Internal error: can't find deserializer for void
at [Source: N/A; line: -1, column: -1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3512)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3453)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3441)
	at com.github.therapi.jsonrpc.client.ServiceFactory.lambda$createService$0(ServiceFactory.java:56)
	at com.sun.proxy.$Proxy5.delete(Unknown Source)
	at SDK.main(SDK.java:19)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Internal error: can't find deserializer for void
at [Source: N/A; line: -1, column: -1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:251)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3890)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3505)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Internal error: can't find deserializer for void
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers.find(NumberDeserializers.java:107)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1591)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:133)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 10 more

Is that something you can take a look at?

Thanks.

Paul

**Comment by dnault** [comment]
Thanks Paul. Fixed.

**Comment by pvangool** [comment]
Thanks!

Paul

> On May 26, 2016, at 2:24 PM, dnault <notifications@github.com> wrote:
> 
> Thanks Paul. Fixed.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/dnault/therapi-json-rpc/issues/2#issuecomment-221999131>

--
Paul van Gool
pvangool@gmail.com
